# scratch downloads
FROM scratch as scratch

ADD https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz /app/
ADD https://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz /app/
ADD https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz /app/

RUN mkdir /dist/ && \
    cd /app/ && \
    tar -xzvf GeoLite2-ASN.tar.gz && \
    tar -xzvf GeoLite2-City.tar.gz && \
    tar -xzvf GeoLite2-Country.tar.gz && \
    cp */*.mmdb /dist/

# set up environment
FROM golang:1.13-alpine AS build
ARG BUILDPATH=github.com/jnovack/docker-ipinfo

COPY --from=scratch /dist/*.mmdb /app/

RUN apk -U add git

COPY * /go/src/${BUILDPATH}/

RUN go get -v

WORKDIR /go/src/${BUILDPATH}/
